runtime: nodejs12
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
  http_headers:
    Access-Control-Allow-Origin: https://stevent-backend.ts.r.appspot.com
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  http_headers:
    Access-Control-Allow-Origin: https://stevent-backend.ts.r.appspot.com
